import Image from "next/image";
import Link from "next/link";
import HeroBottle from "@/components/HeroBottle";
import BrandForms from "@/components/BrandForms";
import "./brand.css";

const faqs = [
  ["What is HEVON?", "HEVON is an Indian everyday nutrition brand in development. We’re starting with a ready-to-drink protein coffee, built around the coffee experience you actually look forward to."],
  ["Can I buy it yet?", "Not yet. Join the launch list and we’ll share availability, pricing and ordering details when the first product is ready. Joining is free and is not a pre-order."],
  ["How much protein will it have?", "Our development target is 20–25g protein in a 250ml bottle, subject to taste, texture and stability. Final nutrition, ingredients, allergens and caffeine information will be shared before sale. Images show a packaging concept."],
  ["Is HEVON only for people who work out?", "We’re designing HEVON for everyday coffee drinkers as well as active lifestyles. You’ll be able to review the final ingredients and nutrition information to decide whether it fits your routine."],
  ["How can I give feedback?", "Open our taste feedback form after trying HEVON. Only your taste rating is required. You can also tell us about sweetness, texture and what you’d like next. Nutrition preferences and contact details are optional."],
  ["What’s next beyond coffee?", "Our ambition is to make everyday nutrition more useful and personal over time. Your preferences will help guide future flavours, products and experiences. These are future ideas, not services available today."],
];

export default function Home() {
  return <div className="hv-brand">
    <a className="hv-skip" href="#main">Skip to content</a>
    <div className="hv-announcement">A higher you, every day. <span>Protein coffee is coming.</span><a href="#waitlist">Be first to know ↗</a></div>
    <header className="hv-header"><Link href="/" aria-label="HEVON home" className="hv-logo"><Image src="/logo/hevon-wordmark.svg" alt="HEVON" width={140} height={38} priority /></Link><nav className="hv-desktop-nav" aria-label="Main navigation"><a href="#coffee">Meet the coffee</a><a href="#story">Our story</a><a href="#next">What’s next</a><a href="/feedback.html">Share feedback</a></nav><a className="hv-nav-cta" href="#waitlist">Join the launch <span aria-hidden="true">↗</span></a><details className="hv-mobile-menu"><summary aria-label="Open navigation">☰</summary><nav aria-label="Mobile navigation"><a href="#coffee">Meet the coffee</a><a href="#story">Our story</a><a href="#next">What’s next</a><a href="/feedback.html">Share feedback</a><a href="#faq">Questions & answers</a></nav></details></header>
    <main id="main">
      <section className="hv-hero" aria-labelledby="hero-title"><div className="hv-hero-copy"><p className="hv-kicker"><span /> GOOD DAYS START HERE</p><h1 id="hero-title">Your coffee.<br />With a little<br /><em>more in it.</em></h1><p className="hv-lead">The coffee ritual you love. The protein you’re looking for. Meet HEVON’s first everyday nutrition idea.</p><div className="hv-actions"><a className="hv-button hv-button-dark" href="#waitlist">Get launch updates <span aria-hidden="true">↗</span></a><a className="hv-text-link" href="#coffee">Meet your next coffee ↓</a></div><p className="hv-hero-foot">COFFEE FIRST. NUTRITION WITH PURPOSE.</p></div><figure className="hv-hero-visual"><Image src="/hevon-campaign-2026.png" alt="HEVON iced coffee bottle concept with a glass of iced coffee in warm sunlight" width={1122} height={1402} priority sizes="(max-width: 760px) 100vw, 50vw" /><figcaption>Packaging concept · final product details at launch</figcaption><span className="hv-image-label">MEET HEVON<br /><b>More than<br />coffee.</b></span></figure></section>
      <div className="hv-ribbon" aria-label="Our approach"><span>Coffee comes first</span><i aria-hidden="true">✳</i><span>Built for real routines</span><i aria-hidden="true">✳</i><span>Shaped by you</span><i aria-hidden="true">✳</i><span>A higher you, every day</span></div>
      <section id="coffee" className="hv-section hv-product"><div className="hv-product-heading"><p className="hv-kicker">THE FIRST CHAPTER</p><h2>Big coffee energy.<br /><em>Everyday ambition.</em></h2></div><div className="hv-product-content"><div><span className="hv-tag">IN DEVELOPMENT</span><h3>Protein Iced Coffee</h3><p>We’re working on a rich, smooth coffee you can grab and go. A familiar daily ritual, with meaningful protein built in.</p><a className="hv-text-link" href="#waitlist">Save me a place on the launch list ↗</a></div><dl className="hv-specs"><div><dt>20–25g</dt><dd>Protein development target</dd></div><div><dt>250ml</dt><dd>Planned bottle size</dd></div><div><dt>Taste first</dt><dd>Our starting point, always</dd></div></dl></div><p className="hv-small">We’re refining the recipe. Final nutrition, ingredients and availability will be confirmed before sale.</p><details className="hv-bottle-explore"><summary>Explore the bottle concept <span aria-hidden="true">+</span></summary><HeroBottle /><p className="hv-small">Drag the bottle or use the rotation buttons. Packaging is a concept; final details will be shared at launch.</p></details></section>
      <section id="taste-lab" className="hv-feedback"><div><p className="hv-kicker">YOUR TASTE. OUR NEXT STEP.</p><h2>Had a sip?<br />Tell us <em>everything.</em></h2><p>Loved it? Too sweet? Want something different?<br />Your honest feedback helps us make HEVON better.</p><a className="hv-button hv-button-dark" href="/feedback.html">Share my taste feedback <span aria-hidden="true">↗</span></a><span className="hv-feedback-note">About a minute. No account needed.</span></div><div className="hv-feedback-card"><span className="hv-tag">THE HEVON TASTE CHECK</span><h3>How was<br />your first sip?</h3><div className="hv-rating-preview" aria-hidden="true">★ ★ ★ ★ ★</div><p>You bring the honest opinion.<br />We’ll bring the listening.</p><div className="hv-feedback-card-bottom"><span>Taste · Sweetness · Texture</span><span aria-hidden="true">↗</span></div></div></section>
      <section id="next" className="hv-section hv-next"><div><p className="hv-kicker">GOOD THINGS START WITH YOU</p><h2>What should<br />we stir up <em>next?</em></h2><p>Coffee is our first chapter. Help us choose the flavours worth exploring after it.</p><p className="hv-small">These are future concepts, not products available to buy.</p></div><BrandForms kind="vote" /></section>
      <section id="story" className="hv-story"><div className="hv-story-mark" aria-hidden="true">A HIGHER<br /><span>YOU.</span><br />EVERY DAY.</div><div><p className="hv-kicker">WHY WE’RE HERE</p><h2>Better nutrition.<br />A little more <em>everyday.</em></h2><p>We believe looking after yourself should feel like part of your life. Not another complicated thing on your to-do list.</p><p>So we’re starting with something familiar: coffee. Making it work a little harder for your day, while keeping taste at the heart of it.</p><p>Our ambition goes beyond one bottle. We’re building HEVON around real routines, honest feedback and the nutrition people actually want.</p><a className="hv-text-link" href="mailto:hello@hevon.in">Say hello to HEVON ↗</a></div></section>
      <section id="faq" className="hv-section hv-faq"><div><p className="hv-kicker">GLAD YOU ASKED</p><h2>A few things<br />to <em>know.</em></h2></div><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}{question === "How can I give feedback?" && <> <a href="/feedback.html">Open the feedback form ↗</a></>}</p></details>)}</div></section>
      <section id="waitlist" className="hv-launch"><div><p className="hv-kicker">BE PART OF THE FIRST CHAPTER</p><h2>Your next<br />coffee ritual<br /><em>starts here.</em></h2><p>Join the HEVON launch list for product news,<br />early-access information and what’s coming next.</p></div><BrandForms kind="waitlist" /></section>
    </main>
    <footer className="hv-footer"><div className="hv-footer-top"><Link href="/" aria-label="HEVON home"><Image src="/logo/hevon-wordmark.svg" alt="HEVON" width={168} height={46} /></Link><p>A higher you. Every day.</p><a href="https://instagram.com/hevonofficial" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="mailto:hello@hevon.in">hello@hevon.in ↗</a></div><div className="hv-footer-bottom"><span>© {new Date().getFullYear()} HEVON</span><nav aria-label="Footer navigation"><a href="/feedback.html">Taste feedback</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav><span>Made for everyday ambition.</span></div></footer>
  </div>;
}
