"use client";

import { FormEvent, useMemo, useState } from "react";
import { Calculator, LoaderCircle } from "lucide-react";
import { useRouter } from "next/navigation";

export default function ProteinCalculator() {
  const router = useRouter(); const [weight, setWeight] = useState(60); const [age, setAge] = useState(""); const [gender, setGender] = useState(""); const [status, setStatus] = useState<"idle" | "submitting" | "error">("idle"); const estimate = useMemo(() => Math.round(weight * 0.83), [weight]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("submitting"); const data = new FormData(event.currentTarget); data.set("weight-kg", String(weight)); data.set("age-band", age); data.set("gender", gender); data.set("estimated-protein-g", String(estimate)); const body = new URLSearchParams(); data.forEach((value, key) => body.append(key, String(value))); try { const response = await fetch("/", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: body.toString() }); if (!response.ok) throw new Error(); router.push("/success?form=protein"); } catch { setStatus("error"); } }
  return <section id="my-protein" className="scroll-mt-20 bg-white px-5 py-20 sm:px-6 sm:py-24 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 rounded-[38px] bg-[#111] p-6 text-white shadow-[0_30px_90px_rgba(0,0,0,.14)] sm:p-10 lg:grid-cols-[.8fr_1.2fr] lg:p-14">
    <div><p className="eyebrow">Know Your Protein Number</p><h2 className="section-title mt-5 text-white">Make protein<br /><span className="font-serif italic text-[#ff8b3d]">personal.</span></h2><p className="mt-6 max-w-lg text-sm leading-7 text-white/55">A general ICMR-NIN guideline for healthy Indian adults is about 0.83g per kg of body weight per day. This educational estimate is not medical advice.</p></div>
    <div className="rounded-[30px] bg-white p-5 text-[#111] sm:p-8"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-black uppercase tracking-[.12em] text-black/45">Age<select required aria-label="Age group" value={age} onChange={(event) => setAge(event.target.value)} className="mt-2 min-h-13 w-full rounded-2xl border border-black/10 bg-white px-4 text-base font-medium normal-case tracking-normal text-[#111] outline-none focus:border-[#ff6a00]"><option value="" disabled>Select age</option><option>18–24</option><option>25–34</option><option>35–44</option><option>45–54</option><option>55–64</option><option>65+</option></select></label><label className="text-xs font-black uppercase tracking-[.12em] text-black/45">Gender<select required aria-label="Gender" value={gender} onChange={(event) => setGender(event.target.value)} className="mt-2 min-h-13 w-full rounded-2xl border border-black/10 bg-white px-4 text-base font-medium normal-case tracking-normal text-[#111] outline-none focus:border-[#ff6a00]"><option value="" disabled>Select gender</option><option>Woman</option><option>Man</option><option>Non-binary</option><option>Prefer not to say</option></select></label></div><label className="mt-5 block text-xs font-black uppercase tracking-[.14em] text-black/45">Your body weight</label><div className="mt-4 flex items-center gap-3"><input aria-label="Body weight in kilograms" type="range" min="40" max="120" value={weight} onChange={(e) => setWeight(Number(e.target.value))} className="w-full accent-[#ff6a00]" /><div className="min-w-20 rounded-2xl bg-[#fff1e7] px-4 py-3 text-center text-xl font-black">{weight}kg</div></div><div className="mt-6 rounded-[24px] bg-[#ff6a00] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.14em] text-white/65">Estimated daily protein</p><p className="mt-2 text-6xl font-black tracking-[-.06em]">{estimate}g</p><p className="mt-2 text-xs leading-5 text-white/70">Adult baseline estimate. Your actual needs may vary with diet quality, activity, pregnancy or medical conditions.</p></div>
      <form name="hevon-waitlist" onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><input type="hidden" name="form-name" value="hevon-waitlist" /><input type="hidden" name="source" value="HEVON Protein Calculator" /><input type="hidden" name="weight-kg" value={weight} /><input type="hidden" name="age-band" value={age} /><input type="hidden" name="gender" value={gender} /><input type="hidden" name="estimated-protein-g" value={estimate} /><input required type="email" name="email" placeholder="Email my result" className="min-h-14 rounded-full border border-black/10 px-5 text-[#111] outline-none focus:border-[#ff6a00]" /><button disabled={status === "submitting" || !age || !gender} className="button-primary min-h-14 gap-2 disabled:cursor-not-allowed disabled:opacity-45">{status === "submitting" ? <LoaderCircle className="animate-spin" /> : <><Calculator size={17} /> Save result</>}</button></form>{(!age || !gender) && <p className="mt-3 text-xs text-black/45">Select age and gender before saving your result.</p>}{status === "error" && <p className="mt-3 text-sm text-red-600">Unable to save. Please retry.</p>}
    </div>
  </div></section>;
}
